const { AttachmentBuilder } = require('discord.js');

async function createTranscript(channel, limit = 100) {
  try {
    const messages = await channel.messages.fetch({ limit });
    const sorted = [...messages.values()].sort((a, b) => a.createdTimestamp - b.createdTimestamp);

    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Ticket Transcript - #${channel.name}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #1a1a24; color: #e1e1e6; margin: 0; padding: 20px; }
    .header { border-bottom: 2px solid #00A896; padding-bottom: 15px; margin-bottom: 20px; }
    .header h1 { color: #00A896; margin: 0; font-size: 24px; }
    .header p { color: #8a8e94; margin: 5px 0 0 0; font-size: 14px; }
    .message { display: flex; margin-bottom: 16px; padding: 8px; border-radius: 6px; background: #222230; }
    .avatar { width: 42px; height: 42px; border-radius: 50%; margin-right: 12px; }
    .content-box { flex: 1; }
    .author { font-weight: bold; color: #00C4B4; font-size: 15px; margin-right: 8px; }
    .timestamp { font-size: 11px; color: #72767d; }
    .body { margin-top: 4px; font-size: 14px; line-height: 1.4; white-space: pre-wrap; word-break: break-word; }
    .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #72767d; border-top: 1px solid #333; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Ticket Transcript: #${channel.name}</h1>
    <p>Guild: ${channel.guild.name} • Exported at: ${new Date().toUTCString()} • Messages: ${sorted.length}</p>
  </div>
`;

    for (const msg of sorted) {
      const avatarUrl = msg.author.displayAvatarURL({ extension: 'png', size: 64 });
      const time = new Date(msg.createdTimestamp).toLocaleString();
      const content = (msg.cleanContent || msg.content || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

      let attachmentsHtml = '';
      if (msg.attachments.size > 0) {
        attachmentsHtml = msg.attachments.map(att => `<br><a href="${att.url}" target="_blank" style="color:#00A896;">[Attachment: ${att.name}]</a>`).join('');
      }

      let embedsHtml = '';
      if (msg.embeds.length > 0) {
        embedsHtml = msg.embeds.map(e => `<div style="border-left:3px solid #00A896; padding: 4px 8px; margin: 4px 0; background:#181822;"><b>${e.title || ''}</b><br>${e.description || ''}</div>`).join('');
      }

      html += `
  <div class="message">
    <img class="avatar" src="${avatarUrl}" alt="Avatar">
    <div class="content-box">
      <div>
        <span class="author">${msg.author.tag}</span>
        <span class="timestamp">${time}</span>
      </div>
      <div class="body">${content}${attachmentsHtml}${embedsHtml}</div>
    </div>
  </div>`;
    }

    html += `
  <div class="footer">
    Generated by R.O.T.I Bot • Created by itz0cat
  </div>
</body>
</html>`;

    const buffer = Buffer.from(html, 'utf-8');
    return new AttachmentBuilder(buffer, { name: `transcript-${channel.name}.html` });
  } catch (err) {
    console.error('Error generating transcript:', err);
    return null;
  }
}

module.exports = {
  createTranscript
};
